name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies (shellcheck, bats)
        run: |
          sudo apt-get update
          sudo apt-get install -y shellcheck bats

      - name: Lint
        run: make lint

      - name: Test
        run: make test
